import { Instrument } from '../types';

export const SplitMask: Instrument = {
  id: 'splitMask',
  name: 'Split Mask',
  description: 'Splits the scene along a line at a given angle and position',
  icon: '✂️',
  color: '#6366f1',
  hasAudio: false,
  hasVisual: false,
  editorType: 'generic',
  defaultSettings: {
    position: 0.5,
    angle: 0,
    feather: 0.01,
    invert: 0,
    offsetX: 0,
    offsetY: 0,
  },
  settingsSchema: {
    position: {
      type: 'number',
      label: 'Position',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.5,
    },
    angle: {
      type: 'number',
      label: 'Angle',
      min: 0,
      max: 360,
      step: 1,
      default: 0,
    },
    feather: {
      type: 'number',
      label: 'Feather',
      min: 0,
      max: 0.5,
      step: 0.005,
      default: 0.01,
    },
    invert: {
      type: 'number',
      label: 'Invert',
      min: 0,
      max: 1,
      step: 1,
      default: 0,
    },
    offsetX: {
      type: 'number',
      label: 'Offset X',
      min: -1,
      max: 1,
      step: 0.01,
      default: 0,
    },
    offsetY: {
      type: 'number',
      label: 'Offset Y',
      min: -1,
      max: 1,
      step: 0.01,
      default: 0,
    },
  },
};
